### PR TITLE
[docs] Sphinx generated documentation

### PR DESCRIPTION
**Pull request by Dogeek**

### CODE REVIEW

**Comment by Dogeek** [comment]
It's still a WIP, I need to improve on the docs hierarchy, as well as add the docs for the mys packages (in the mys stdlib)

**Comment by pfalcon** [comment]
No review from the project architect? Two important sections - Tutoral and Contributing - completely removed from the README? Nice.

**Comment by eerimoq** [comment]
We discussed the transition from a huge readme to using readthedocs on Discord. These sections were moved to readthedocs. Unfortunately this was merged before the readme was updated with a link to readthedocs. This should be addressed promptly. The move to readthedos is a work in progess, which I hope @Dogeek will continue on soon as documentation is very important, both for Mys users and Mys developers.

**Comment by pfalcon** [comment]
Please keep in mind that "only cowards read the docs", and README is what people see when they hit https://github.com/mys-lang/mys . Having a quick tutorial and quick contrib words in README is rather useful.

**Comment by eerimoq** [comment]
Agree.

**Pull request merged**
